package Enum;

public enum PlayerData {
	numberOfMatchs,
	numberOfStarting ,
	numberOfRebound ,
	numberOfAssist ,
	presentTime ,
	percentageOfShooting ,
	percentageOf3_Point ,
	percentageOfFreeThrow ,
	numberOfAttack ,
	numberOfDefense ,
	numberOfSteal ,
	numberOfBlock ,
	numberOfFault ,
	numberOfFoul ,
	score ,
	
	efficiency ,
	efficiencyOfGmSc ,
	percentageOfTrueShooting ,
	efficiencyOfShooting ,
	percentageOfRebound ,
	percentageOfAttackingRebound ,
	percentageOfDefenseRebound ,
	percentageOfAssist ,
	percentageOfSteal ,
	percentageOfBlock ,
	percentageOfFault ,
	percentageOfUse ,
	numberOfShooting ,
	numberOf3_Point ,
	numberOfFreeThrow ,
	
	double_double ,
	comprehension ,
}
